# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'TweetFromSpace' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TweetFromSpac
  pod 'OAuthSwift', '~> 2.0.0'
  pod 'Swifter', :git => 'https://github.com/mattdonnelly/Swifter.git'

end
