# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'TweetFromSpace' do
  # Pods for TweetFromSpace
  def install_pods
      pod 'Socket.IO-Client-Swift', '~> 15.2.0'
      pod 'OAuthSwift', '~> 2.0.0'
      pod 'GoogleSignIn'
      pod 'Firebase/Auth'
  end
  
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  install_pods

  target 'TweetFromSpaceTests' do
    inherit! :search_paths
    # Pods for testing
#    install_pods
  end

  target 'TweetFromSpaceUITests' do
    # Pods for testing
  end

end
